definitions:
  service.Account:
    properties:
      account_number:
        type: string
      account_type:
        type: string
      address:
        type: string
      balance:
        type: number
      email:
        type: string
      full_name:
        type: string
      has_card:
        type: boolean
      password:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts:
    get:
      description: Fetch all accounts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Account'
            type: array
      summary: Get accounts
      tags:
      - accounts
  /fetch-acc/{acc_num}:
    get:
      description: Fetch an account using the account number
      parameters:
      - description: Account Number
        in: path
        name: acc_num
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Account'
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Account not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get an account by ID
      tags:
      - accounts
  /registers:
    post:
      consumes:
      - application/json
      description: Create a new account
      parameters:
      - description: Account data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/service.Account'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register an account
      tags:
      - accounts
  /update_acc/{acc_num}:
    patch:
      consumes:
      - application/json
      description: Updates the has_card attribute of an account using account_number
      parameters:
      - description: Account Number
        in: path
        name: account_number
        required: true
        type: string
      - description: Updated has_card value
        in: body
        name: request
        required: true
        schema:
          additionalProperties:
            type: boolean
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Account updated OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update HasCard field
      tags:
      - accounts
swagger: "2.0"
